#!/bin/bash
################################################################################
#
# Copyright (c) 2019 NUAA AeroLab
#
# @author   Jiang Yang (pokerpoke@qq.com)
# @date     2019-05
# @brief
# @version  0.0.1
#
# Last Modified:  2019-05-21
# Modified By:    Jiang Yang (pokerpoke@qq.com)
#
################################################################################
set -e

# get scripts directory
CMAKE_SOURCE_DIR=$(dirname $(readlink -f $0))
# update cmake source path
#CMAKE_SOURCE_DIR=$(pwd)
#cd ${CMAKE_SOURCE_DIR}

if [ ! -n "$1" ]; then
    echo "Please input solution."
    exit 1
fi

# src/2.addTwoNumbers.cc -> 2.addTwoNumbers
NAME=$(echo "$1" | awk -F / '{print $NF}' | awk -F '.cc' '{print $1}')
ID=$(echo ${NAME} | sed 's/.[^.]*$//g')
SOLUTION=$(echo ${NAME} | sed 's/^.*\.//g')

cp -f ${CMAKE_SOURCE_DIR}/src/0.template.cc ${CMAKE_SOURCE_DIR}/src/${ID}.${SOLUTION}.cc

sed -i "s/isValid/$(expr ${SOLUTION})/g" \
    ${CMAKE_SOURCE_DIR}/src/${ID}.${SOLUTION}.cc
