#!/bin/bash
################################################################################
# 
# Copyright (c) 2019 NUAA AeroLab
# 
# @author   Jiang Yang (pokerpoke@qq.com)
# @date     2018-08
# @brief    
# @version  0.0.1
# 
# Last Modified:  2019-05-21
# Modified By:    Jiang Yang (pokerpoke@qq.com)
# 
################################################################################
set -e

# get scripts directory
CMAKE_SOURCE_DIR=$(dirname $(readlink -f $0))
# update cmake source path
#CMAKE_SOURCE_DIR=$(pwd)
cd ${CMAKE_SOURCE_DIR}

# src/2.addTwoNumbers.cc -> 2.addTwoNumbers
NAME=$(echo "$1" | awk -F / '{print $NF}' | awk -F '.cc' '{print $1}')

if [ ! -d ./build ] 
then
   mkdir build 
fi

cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug && make ${NAME} -j8 

./src/${NAME}
